/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_CalculateMath */

#ifndef _Included_sample_CalculateMath
#define _Included_sample_CalculateMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_CalculateMath
 * Method:    calcSquare
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sample_CalculateMath_calcSquare
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
